Fixes #10
PromiseFru/contribute-to-open-source pull request #22
Opened 2023-07-08 18:00 UTC by Vanessa-Kris

Please if the images are too big let me know.

2023-07-08 20:52 UTC, PromiseFru requested changes
Hello @Vanessa-Kris

I've dropped some review comments. Please address the issues and I'll carry out another review before merging the pull request.

Thank you for contributing 🚀

2023-07-08 20:52 UTC, PromiseFru commented on images/1.png
Remove unused files

2023-07-08 20:52 UTC, PromiseFru commented on images/3.png
Remove unused files

2023-07-10 10:14 UTC, Vanessa-Kris commented
Updated @PromiseFru

2023-07-10 11:16 UTC, PromiseFru approved these changes

2023-07-10 11:16 UTC, merged